<?php
if(isset($_SESSION["user"])){
  header('Location: index.php?controller=usuarios&action=show_start_page');
}
 ?>
  <!DOCTYPE html>
  <html>

  <head>
    <meta charset="utf-8">
    <title>Login | Green Dragon</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <script src="view/login/js/validation-for-david.js"></script>
    <script src="view/login/js/validation-for-rafa.js"></script>
    <link rel="icon" href="view/login/img/login.png">
    <link rel="stylesheet" type="text/css" href="view/login/style/login_style.css">
  </head>

  <body>
    <div class="container-fluid bg-dark mb-5 pt-2">
      <a href="index.php?controller=productos&action=show_start_page"><img src="view/login/img/main-logo.png" id="top-logo" class="mx-auto d-block" alt="Dragón verde"></img></a>
      <h1 class="text-success text-center pb-3">Green Dragon</h1>
    </div>

    <div class="row">
      <div class="container-fluid col-12 col-lg-8">
        <ul class="nav nav-pills justify-content-center" role="tablist">
          <li class="nav-item col-6 col-sm-6 col-md-4 col-xl-5">
            <a class="nav-link active text-center font-weight-bold" data-toggle="pill" href="#login_tab">LOGIN</a>
          </li>
          <li class="nav-item col-6 col-sm-6 col-md-4 col-xl-5">
            <a class="nav-link text-center font-weight-bold" data-toggle="pill" href="#register_tab">REGISTRO</a>
          </li>
        </ul>
      </div>
    </div>

    <div class="row">
      <div class="tab-content pl-3 pr-3 m-auto">
        <div id="login_tab" class="container tab-pane active"><br>
          <div class="container table-success rounded pt-2 pb-2 col-12">
            <form action="index.php?controller=usuarios&action=login" method="post" class="login-validation" novalidate>
              <div class="row text-center">
                <div class="tab-pane active form-group col-12">
                  <label for="nick" class="font-weight-bold">Nombre de usuario</label>
                  <input id="nick" type="text" class="form-control col-12 font-weight-bold" id="form_nombre" name="username" required>
                  <div class="alert alert-success valid-feedback font-weight-bold" role="alert">
                    ¡Bieeen!
                  </div>
                  <div class="alert alert-danger invalid-feedback font-weight-bold" role="alert">
                    ¡El nombre de usuario no puede estar vacío!
                  </div>
                </div>
                <div class="tab-pane form-group col-12">
                  <label for="passwd" class="font-weight-bold">Contraseña</label>
                  <input id="passwd" type="password" class="form-control col-12 font-weight-bold" name="password" required>

                  <div class="alert alert-success valid-feedback font-weight-bold" role="alert">
                    ¡Bien!
                  </div>

                  <div class="alert alert-danger invalid-feedback font-weight-bold" role="alert">
                    ¡La contraseña no puede estar vacía!
                  </div>
                </div>
              </div>
              <div class="form-group mt-3">
                <button type="submit" class="btn btn-success btn-sm font-weight-bold col-12 pt-2 pb-2" name="login">Entrar</button>
              </div>
            </form>
          </div>
        </div>
        <div id="register_tab" class="container tab-pane fade"><br>
          <div class="container table-success rounded pt-2 pb-2 col-12 col-md-10 col-lg-6 col-xl-5">
            <form action="index.php?controller=usuarios&action=register" method="post" class="register">
              <div class="row text-center">
                <div class=" tab-pane active form-group col-12">
                  <label for="username" class="font-weight-bold">Nombre de usuario</label>
                  <input type="text" class="form-control col-12 font-weight-bold" id="username2" name="username">
                  <span id="infoUser1" ></span>
                </div>
                <div class="tab-pane form-group col-12">
                  <label for="fullname" class="font-weight-bold">Nombre completo</label>
                  <input type="text" class="form-control col-12 font-weight-bold" id="fullname2" name="fullname" >
                  <span id="infoUser2"></span>
                </div>
                <div class="tab-pane form-group col-12">
                  <label for="email" class="font-weight-bold">Correo eletrónico</label>
                  <input type="text" class="form-control col-12 font-weight-bold" id="email2" name="email" >
                  <span id="infoUser3"></span>
                </div>
                <div class="tab-pane form-group col-12">
                  <label for="address" class="font-weight-bold">Dirección</label>
                  <input type="text" class="form-control col-12 font-weight-bold" id="address2" name="address" >
                  <span id="infoUser4"></span>
                </div>
                <div class="tab-pane form-group col-12">
                  <label for="zipCode" class="font-weight-bold">Código postal</label>
                  <input type="text" class="form-control col-12 font-weight-bold" id="zipCode2" name="zipCode" >
                  <span id="infoUser5"></span>
                </div>
                <div class="tab-pane form-group col-12">
                  <label for="password" class="font-weight-bold">Contraseña</label>
                  <input type="password" class="form-control col-12 font-weight-bold" id="password2" name="password">
                  <span id="infoUser6"></span>
                  <small id="infoPasswd"></small>
                </div>
                <div class="tab-pane form-group col-12">
                  <label for="password2" class="font-weight-bold">Repite contraseña</label>
                  <input type="password" class="form-control col-12 font-weight-bold" id="password_check2" name="password_check" >
                  <span id="infoUser7"></span>
                </div>
              </div>
              <div class="form-group mt-3">
                <button type="submit" class="btn btn-success font-weight-bold col-12 pt-2 pb-2" name="login">Registrarse</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>





  </body>

  </html>
