<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Login | Green Dragon</title>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  <link rel="icon" href="view/login/img/login.png">
  <link rel="stylesheet" type="text/css" href="view/login/style/login_style.css">
</head>

<body>
  <div class="container-fluid bg-dark mb-5 pt-2">
    <img src="view/login/img/main-logo.png" id="top-logo" class="mx-auto d-block" alt="Dragón verde"></img>
    <hr class="bg-muted">
    <h1 class="text-success text-center pb-3">Green Dragon</h1>
  </div>
  <div class="container-fluid">
    <ul class="nav nav-pills" role="tablist">
      <li class="nav-item col-6 col-sm-5 col-md-4 col-xl-5">
        <a class="nav-link active" data-toggle="pill" href="#login_tab">Login</a>
      </li>
      <li class="nav-item col-6 col-sm-5 col-md-4 col-xl-5">
        <a class="nav-link" data-toggle="pill" href="#register_tab">Registro</a>
      </li>
    </ul>

    <div class="tab-content">
      <div id="login_tab" class="container tab-pane active"><br>
        <div class="container table-success col-12 col-sm-9 col-md-7 col-xl-4">
          <form action="index.php?controller=usuarios&action=login" method="post">
            <div class="row text-center">
              <div class="container tab-pane active form-group col-6">
                <label for="form_nombre" class="font-weight-bold">Nombre de usuario</label>
                <input type="text" class="form-control col-12 font-weight-bold" id="form_nombre" name="username">
              </div>
              <div class="container tab-pane form-group col-6">
                <label for="form_nombre" class="font-weight-bold">Contraseña</label>
                <input type="password" class="form-control col-12 font-weight-bold" name="password">
              </div>
            </div>
            <div class="form-group col-6">
              <button type="submit" class="btn btn-success font-weight-bold col-12 pt-2 pb-2" name="login">Entrar</button>
            </div>
          </form>
        </div>
      </div>
      <div id="register_tab" class="container tab-pane fade"><br>
        <div class="container table-success col-12 col-sm-9 col-md-7 col-xl-4">
          <form action="index.php?controller=usuarios&action=register" method="post">
            <div class="row text-center">
              <div class="container tab-pane active form-group col-6">
                <label for="form_nombre" class="font-weight-bold">Nombre de usuario</label>
                <input type="text" class="form-control col-12 font-weight-bold" id="form_nombre" name="username">
              </div>
              <div class="container tab-pane form-group col-6">
                <label for="form_nombre" class="font-weight-bold">Contraseña</label>
                <input type="password" class="form-control col-12 font-weight-bold" name="password">
              </div>
            </div>
            <div class="form-group col-6">
              <button type="submit" class="btn btn-success font-weight-bold col-12 pt-2 pb-2" name="login">Registrarse</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>










</body>

</html>
