<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Administrador | Productos</title>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  <link rel="icon" href="view/admin/img/icon.png">
  <link rel="stylesheet" type="text/css" href="../style/productos_style.css">
</head>

<body>
  <div class="container">
        <h3>Insertar un nuevo producto</h3>
        <form action="index.php?controller=productos&action=insert" method="post">
          <div class="row text-center">
            <div class="container  active form-group">
              <label for="form_nombre" class="font-weight-bold">Nombre</label>
              <input type="text" class="form-control col-12 font-weight-bold" name="name">
            </div>
            <div class="container  form-group">
              <label for="stock" class="font-weight-bold">Stock</label>
              <input type="text" class="form-control col-12 font-weight-bold" name="stock">
            </div>
            <div class="container  active form-group">
              <label for="price" class="font-weight-bold">Precio</label>
              <input type="text" class="form-control col-12 font-weight-bold" name="price">
            </div>
            <div class="container  active form-group">
              <label for="shrtDesc" class="font-weight-bold">Descripción corta</label>
              <textarea rows="2" class="form-control txtNoResizable" name="shortDesc"></textarea>
            </div>
            <div class="container  form-group">
              <label for="$lngDesc" class="font-weight-bold">Descripción larga</label>
              <textarea rows="5" class="form-control txtNoResizable" name="$longDesc"></textarea>
            </div>
            <div class="container  active form-group">
              <label for="brand" class="font-weight-bold">Marca</label>
              <input type="text" class="form-control col-12 font-weight-bold" name="brand">
            </div>
            <div class="container  form-group">
              <label for="category" class="font-weight-bold">Categoría</label>
              <?php
              include("view/admin/php/listar_categorias.php");
              ?>
            </div>
            <div class="container  form-group">
              <label for="category" class="font-weight-bold">Subcategoría</label>
              <select class="form-control form-control-sm" name="">
                <option value="sN">No</option>
                <option value="sY">Sí</option>
              </select>
            </div>
            <div class="container form-group">
              <label for="form_nombre" class="font-weight-bold">Patrocinado</label>
              <select class="form-control form-control-sm" name="sponsored">
                <option value="sN">No</option>
                <option value="sY">Sí</option>
              </select>
            </div>
          </div>
          <div class="form-group col-6">
            <button type="submit" class="btn btn-success font-weight-bold col-12 pt-2 pb-2" name="insert">Insertar</button>
          </div>
        </form>
      </div>
</body>

</html>
