
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Administrador | Productos</title>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  <link rel="icon" href="view/admin/img/icon.png">
  <link rel="stylesheet" type="text/css" href="../style/productos_style.css">
</head>

<body>
  <div class="container">
    <br>
    <ul class="nav nav-pills" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="pill" href="#insert">I</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="pill" href="#delete">D</a>
      </li>
    </ul>

    <div class="tab-content">
      <div id="insert" class="container tab-pane active"><br>
        <h3>Insertar un nuevo producto</h3>
        <form action="index.php?controller=productos&action=insert" method="post">
          <div class="row text-center">
            <div class="container tab-pane active form-group">
              <label for="form_nombre" class="font-weight-bold">Nombre</label>
              <input type="text" class="form-control col-12 font-weight-bold" name="name">
            </div>
            <div class="container tab-pane form-group">
              <label for="stock" class="font-weight-bold">Stock</label>
              <input type="text" class="form-control col-12 font-weight-bold" name="stock">
            </div>
            <div class="container tab-pane active form-group">
              <label for="price" class="font-weight-bold">Precio</label>
              <input type="text" class="form-control col-12 font-weight-bold" name="price">
            </div>
            <div class="container tab-pane active form-group">
              <label for="shrtDesc" class="font-weight-bold">Descripción corta</label>
              <textarea rows="2" class="form-control txtNoResizable" name="shortDesc"></textarea>
            </div>
            <div class="container tab-pane form-group">
              <label for="$lngDesc" class="font-weight-bold">Descripción larga</label>
              <textarea rows="5" class="form-control txtNoResizable" name="$longDesc"></textarea>
            </div>
            <div class="container tab-pane active form-group">
              <label for="brand" class="font-weight-bold">Marca</label>
              <select class="form-control form-control-lg" name="marca">
              <?php
              foreach ($datosBrand as $dato) { ?>
                <?php echo "<option value='{$dato['ID']}'>{$dato['NAME']}</option>" ?>
              <?php
              } ?>
              </select>

            </div>
            <div class="container tab-pane form-group">
              <label for="category" class="font-weight-bold">Categoría</label>
              <select class="form-control form-control-lg" name="categoriaPadre">
              <?php
              foreach ($datosCtg as $dato) { ?>
                <?php echo "<option value='{$dato['ID']}'>{$dato['NAME']}</option>" ?>
              <?php   } ?>
              </select>

            </div>
            <div class="container tab-pane form-group">
              <label for="category" class="font-weight-bold">Subcategoría</label>
              <select class="form-control form-control-sm" name="">
                <option value="sN">No</option>
                <option value="sY">Sí</option>
              </select>
            </div>
            <div class="container tab-pane form-group">
              <label for="form_nombre" class="font-weight-bold">Patrocinado</label>
              <select class="form-control form-control-sm" name="sponsored">
                <option value="sN">No</option>
                <option value="sY">Sí</option>
              </select>
            </div>
          </div>
          <div class="form-group col-6">
            <button type="submit" class="btn btn-success font-weight-bold col-12 pt-2 pb-2" name="insert">Insertar</button>
          </div>
        </form>
      </div>
      <div id="delete" class="container tab-pane fade"><br>
        <h3>Eliminar producto</h3>
        <form action="index.php?controller=productos&action=delete" method="post">
          <div class="row text-center">
            <p>AQUÍ IRÁ EL LISTADO DE TODOS LOS PRODUCTOS.</p>
            <table class="table table-dark table-hover">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>NOMBRE</th>
                  <th>STOCK</th>
                  <th>PRECIO</th>
                  <th>PATROCINADO</th>
                  <th>DESCRIPCIÓN CORTA</th>
                </tr>
              </thead>
              <tbody>
<?php foreach ($datos as $dato) { ?>
                <tr>
                  <td><?php echo $dato['ID']; ?></td>
                  <td><?php echo $dato['NAME']; ?></td>
                  <td><?php echo $dato['STOCK']; ?></td>
                  <td><?php echo money_format('%.2n', $dato['PRICE']); ?> €</td>
                  <td><?php echo $dato['SPONSORED']; ?></td>
                  <td><?php echo $dato['SHORTDESCRIPTION']; ?></td>
                  <td><?php echo "<a href=\"index.php?controller=productos&action=delete&ID={$dato['ID']}\">Borrar</a><br/>";?></td>
                </tr>
<?php  } ?>
              </tbody>
            </table>
          </div>
          <div class="form-group col-6">
            <button type="submit" class="btn btn-success font-weight-bold col-12 pt-2 pb-2" name="delete">Borrar</button>
          </div>
      </div>
      </form>
    </div>
    <form action="index.php?controller=productos&action=show_start_page" method="post">
      <input type="submit" class="btn btn-danger" value="Página Inicio" />
    </form>
  </div>
  </div>
</body>

</html>
