<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Administrador | Productos</title>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  <link rel="icon" href="view/admin/img/icon.png">
  <link rel="stylesheet" type="text/css" href="view/admin/style/productos_style.css">
</head>

<body>
  <div class="container">
    <br>
    <ul class="nav nav-pills col-12 text-center" role="tablist">
      <li class="nav-item col-12">
        <a class="nav-link active" data-toggle="pill" href="#insert">Insertar Producto</a>
      </li>
      <li class="nav-item col-12">
        <a class="nav-link" data-toggle="pill" href="#delete">Eliminar Producto (BETA)</a>
      </li>
      <li class="nav-item col-12">
        <a class="nav-link" data-toggle="pill" href="#promotion">Añadir Promoción</a>
      </li>
    </ul>

    <div class="tab-content">
      <div id="insert" class="container tab-pane active"><br>
        <h3 class="text-center font-weight-bold">Insertar un nuevo producto</h3><hr>
        <form action="index.php?controller=productos&action=insert" method="post" class="col-12">
          <div class="row text-center">
            <div class="container tab-pane active form-group">
              <label for="form_nombre" class="font-weight-bold">Nombre</label>
              <input type="text" class="form-control col-12 font-weight-bold" name="name" required minlength="1" maxlength="32">
            </div>
            <div class="container tab-pane form-group">
              <label for="stock" class="font-weight-bold">Stock</label>
              <input type="number" class="form-control col-12 font-weight-bold" name="stock" required min="1">
            </div>
            <div class="container tab-pane active form-group">
              <label for="price" class="font-weight-bold">Precio</label>
              <input type="number" class="form-control col-12 font-weight-bold" name="price" required min="1">
            </div>
            <div class="container tab-pane active form-group">
              <label for="shrtDesc" class="font-weight-bold">Descripción corta</label>
              <textarea rows="2" class="form-control txtNoResizable" name="shortDesc" maxlength="128"></textarea>
            </div>
            <div class="container tab-pane form-group">
              <label for="$lngDesc" class="font-weight-bold">Descripción larga</label>
              <textarea rows="5" class="form-control txtNoResizable" name="longDesc" maxlength="1024"></textarea>
            </div>
            <div class="container tab-pane active form-group">
              <label for="brand" class="font-weight-bold">Marca</label>
              <select class="form-control" name="brand">
              <?php
              foreach ($brands as $dato) { ?>
                <?php echo "<option value='{$dato['ID']}'>{$dato['NAME']}</option>" ?>
              <?php
              } ?>
              </select>

            </div>
            <div class="container tab-pane form-group">

              <label for="category" class="font-weight-bold">Categoría</label>
              <select class="form-control" name="category">
              <?php
              foreach ($categories as $dato) { ?>
                <?php echo "<option value='{$dato['ID']}'>{$dato['NAME']}</option>" ?>
              <?php   } ?>
              </select>

            </div>
            <div class="container tab-pane form-group">
              <label for="category" class="font-weight-bold">Subcategoría</label>
              <select class="form-control" name="subcategory">
                  <?php
                  foreach ($subCategories as $dato) {
                    if ($dato['PARENTCATEGORY'] != NULL) { ?>
                      <?php echo "<option value='{$dato['ID']}'>{$dato['SUBCATEGORIA']}</option>" ?>
                  <?php
                  }
                   } ?>
                </select>
            </div>
            <div class="container tab-pane form-group">
              <label for="form_nombre" class="font-weight-bold">Patrocinado</label>
              <select class="form-control" name="sponsored">
                <option value="N">No</option>
                <option value="Y">Sí</option>
              </select>
            </div>
          </div>
          <div class="form-group col-12">
            <button type="submit" class="btn btn-success font-weight-bold col-12 pt-2 pb-2" name="insert">Insertar</button>
          </div>
        </form>
        <div class="col-12 text-center">
        <button type="button" class="btn btn-primary col-12 col-sm-6" data-toggle="modal" data-target="#addCat">Nueva categoría</button>
        <button type="button" class="btn btn-primary col-12 mt-2 col-sm-6" data-toggle="modal" data-target="#addSubCat">Nueva subcategoría</button>
        <button type="button" class="btn btn-primary col-12 mt-2 col-sm-6" data-toggle="modal" data-target="#addPrdImg">Nueva imagen</button>
      </div>
      </div>
      <div id="delete" class="container tab-pane fade"><br>
        <h3 class="text-center font-weight-bold">Eliminar producto (versión BETA)</h3><hr>
        <form action="index.php?controller=productos&action=delete" method="post" class="text-center">
          <small class="font-italic mb-2">No usar, SOLO se puede borrar productos sin claves foráneas.</small>
          <div class="row text-center">
            <table class="table table-dark table-hover table-responsive">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>NOMBRE</th>
                  <th>STOCK</th>
                  <th>PRECIO</th>
                  <th>PATROCINADO</th>
                  <th>DESCRIPCIÓN CORTA</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach ($datos as $dato) { ?>
                <tr>
                  <td>
                    <?php echo $dato['ID']; ?>
                  </td>
                  <td>
                    <?php echo $dato['NAME']; ?>
                  </td>
                  <td>
                    <?php echo $dato['STOCK']; ?>
                  </td>
                  <td>
                    <?php echo enEuro($dato['PRICE']); ?>
                  </td>
                  <td>
                    <?php echo $dato['SPONSORED']; ?>
                  </td>
                  <td>
                    <?php echo $dato['SHORTDESCRIPTION']; ?>
                  </td>
                  <td>
                    <a class="btn btn-danger disabled" href="index.php?controller=productos&action=delete&ID=<?php echo $dato['ID']?>">Borrar</a>
                  </td>
                </tr>
                <?php  } ?>
              </tbody>
            </table>
          </div>
        </form>
      </div>
      <div id="promotion" class="container tab-pane fade table-responsive"><br>
        <h3 class="text-center font-weight-bold">Crear promoción</h3><hr>
        <form action="index.php?controller=productos&action=create_promotion" method="post">
          <div class="row text-center">
            <table class="table table-dark table-hover">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>NOMBRE</th>
                  <th>PRECIO</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach ($notSponsoredPrd as $dato) {?>
                <tr>
                  <td>
                    <?php echo $dato['ID']; ?>
                  </td>
                  <td>
                    <?php echo $dato['NAME']; ?>
                  </td>
                  <td>
                    <?php echo enEuro($dato['PRICE']); ?>
                  </td>
                  <td><button type="button" class="btn btn-success" data-toggle="modal" data-target="#addProm<?php echo $dato['ID']; ?>">Crear promoción</button></td>
                </tr>
                <?php }?>
              </tbody>
            </table>
          </div>
        </form>
        <script>
          function mostra_amb_ajax(precio, id, idProducto) {
            //Agafo el valor de la casella d'input
            var descuento = document.getElementById(id).value;

            /* Una XML HTTP Request permet executar codi en el servidor
             * sense recarregar la pàgina web. És el que es coneix com a "AJAX" */
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function() {
              if (this.readyState == 4 && this.status == 200) {
                document.getElementById("zona_ajax" + idProducto).innerHTML = this.responseText;
              }
            }
            //Paso la variable   nom   com a paràmetre del fitxer  texto2.php
            xmlhttp.open("GET", "view/admin/ajax/respuestaAjax.php?descuento=" + descuento + "&precio=" + precio, true);
            xmlhttp.send();
          }
        </script>
        <?php foreach ($notSponsoredPrd as $dato) {?>
        <div id="addProm<?php echo $dato['ID']; ?>" class="modal fade">
          <form action="index.php?controller=productos&action=create_promotion&ID=<?php echo $dato['ID'];?>" method="post">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title">Añadir promoción - <?php echo $dato['NAME']; ?></h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                  <div class="container tab-pane active form-group">
                    <label for="prmDis" class="font-weight-bold col-12 text-center">Rango del descuento (1-99%)</label>
                    <input type="number" class="form-control font-weight-bold" name="prmDis" id="prmDis<?php echo $dato['ID']; ?>" onkeyup="mostra_amb_ajax(<?php echo $dato['PRICE']; ?>,'prmDis<?php echo $dato['ID']; ?>',<?php echo $dato['ID']; ?>)" min="1" max="99">
                    <div id="zona_ajax<?php echo $dato['ID']; ?>"></div>
                  </div>
                  <div class="container tab-pane active form-inline">
                    <label for="prmyrStrt" class="font-weight-bold col-12">Fecha inicio (actual)</label>
                    <input type="text" class="form-control col-4" name="prmyrStrt" id="prmyrStrt" value="<?php echo YEAR ?>" disabled>
                    <input type="text" class="form-control col-4" name="prmmthStrt" id="prmmthStrt" value="<?php echo MONTH ?>" disabled>
                    <input type="text" class="form-control col-4" name="prmdayStrt" id="prmdayStrt" value="<?php echo DAY ?>" disabled>
                    <label for="prmyr" class="font-weight-bold col-12">Fecha final (Año-mes-día)</label>
                    <input type="number" class="form-control col-4" name="prmyr" id="prmyr" placeholder="<?php echo YEAR ?>" min="<?php echo YEAR ?>" max="9999" required>
                    <input type="number" class="form-control col-4" name="prmmth" id="prmmth" placeholder="<?php echo MONTH ?>" min="1" max="12" required>
                    <input type="number" class="form-control col-4" name="prmday" id="prmday" placeholder="<?php echo DAY+1 ?>" min="1" max="31" required>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-outline-success">Añadir</button>
                </div>
              </div>
            </div>
          </form>
        </div>
        <?php  } ?>
      </div>
    </div>
    <form action="index.php?controller=productos&action=show_start_page" method="post">
      <input type="submit" class="btn btn-danger btn-lg col-12 mt-2 mb-1" value="Página Inicio" />
    </form>
  </div>
  <div class="modal fade" id="addCat">
    <form action="index.php?controller=categorias&action=insert_category" method="post">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Añadir cateogría</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <div class="container tab-pane active form-group">
              <label for="nmCat" class="font-weight-bold">Nombre</label>
              <input type="text" class="form-control col-12 font-weight-bold" name="nmCat" id="nmCat">
            </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-outline-success">Añadir</button>
          </div>
        </div>
      </div>
    </form>
  </div>
  <div class="modal fade" id="addPrdImg">
    <form action='index.php?controller=imagenes&action=insert_image' method="post" enctype='multipart/form-data'>
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Añadir imagen</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <input type="file" name="imgUrl"><br>
              <small class="form-text text-muted">Recuerda: el nombre de la imagen se establecerá automáticamente.</small>
              <small class="form-text text-info font-italic">Se añadirá al producto con la ID <strong><u><?php foreach ($productId as $prdId) { echo $prdId['PRODUCTMAXID'];?></u></strong>.</small>
              <input class="oculto" type="text" name="id" value="<?php echo $prdId['PRODUCTMAXID'];?>" <?php } ?>>
            </div>
            <div class="form-group">
              <label for="isCarousel">¿Pertenece a un carrusel?</label>
              <select id="isCarousel" name="isCarousel" class="form-control">
                <option value="N">No</option>
                <option value="Y">Sí</option>
              </select>
            </div>
            <div class="form-group">
              <label for="0">¿De qué tipo será la imagen?</label>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="typeimg" id="0" value="option1" checked>
                <label class="form-check-label" for="0">Portada del producto (tarjetas).</label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="typeimg" id="1" value="option2">
                <label class="form-check-label" for="1">Carrusel en la página de inicio.</label>
                <small id="1" class="form-text text-warning">Si seleccionas esta opción el valor del carrusel debe estar marcado como <strong>(Sí)</strong>.</small>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="typeimg" id="2" value="option3">
                <label class="form-check-label" for="2">Secundaria del producto.</label>
                <small id="2" class="form-text text-warning">Si seleccionas esta opción el valor del carrusel debe estar marcado como <strong>(Sí)</strong>.</small>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-outline-success col-12">Añadir</button>
          </div>
        </div>
      </div>
    </form>
  </div>
  <div class="modal fade" id="addSubCat">
    <form action="index.php?controller=categorias&action=insert_subCategory" method="post">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Añadir subcategoría</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <div class="container tab-pane active form-group">
              <div class="form-group">
                <label for="nmSbCat">Categoría raíz</label>
                <select id="nmSbCat" class="form-control" name="parentCat">
                <?php
                foreach ($categories as $dato) { ?>
                  <?php echo "<option value='{$dato['ID']}'>{$dato['NAME']}</option>" ?>
                <?php   } ?>
                </select>
                <small id="nmSbCat" class="form-text text-muted font-italic">Es la categoría a la que pertenecerá la nueva subcategoría.</small>
              </div>
              <div class="form-group">
                <label for="subcatName" class="font-weight-bold">Nombre de la subcategoría</label>
                <input type="text" class="form-control col-12" name="subcatName" id="subcatName" required>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-outline-success col-12">Añadir</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</body>

</html>
