<!DOCTYPE html>
<html>

<head>

  <head>
    <meta charset="utf-8">
    <title>Administrador | Productos</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link rel="icon" href="view/admin/img/icon.png">
  </head>
</head>

<body>
  <div class="container bg-warning mt-5">
    <form action="index.php?controller=productos&action=show_insert_page" method="post" class="pb-3 text-center">
      <button type="submit" name="button" class="btn btn-success btn-lg w-50">Insertar</button>
    </form>
    <form action="index.php?controller=productos&action=show_update_page" method="post" class="pb-3 text-center">
      <button type="submit" name="button" class="btn btn-success btn-lg w-50">Modificar</button>
    </form>
    <form action="index.php?controller=productos&action=show_delete_page" method="post" class="pb-5 text-center">
      <button type="submit" name="button" class="btn btn-success btn-lg w-50">Eliminar</button>
    </form>
    <form action="index.php?controller=productos&action=show_manage_product" method="post" class="pt-3 text-center">
      <button type="submit" name="button" class="btn btn-success btn-lg w-100">Salir de la zona admin</button>

    </form>
  </div>
</body>

</html>
