<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>GreenDragon - tu carrito</title>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  <link rel="icon" href="view/main/img/main-logo.png">
  <link rel="stylesheet" type="text/css" href="view/main/style/cart_page_style.css">
</head>

<body>
  <?php include("view/main/php/header.php"); ?>

  <?php $Tprice = 0; ?>
  <div class="container">
    <table id="cart" class="table table-hover table-condensed">
      <?php if (empty($_SESSION['cart'])) {
          echo "<h2>No hay artículos en tu carrito<h2>";
        } else {?>

      <thead>
        <tr>
          <th style="width:50%">Producto</th>
          <th style="width:10%">Precio</th>
          <th style="width:8%">Cantidad</th>
          <th style="width:22%" class="text-center">Precio Total</th>
          <th style="width:10%"></th>
        </tr>
      </thead>
      <tbody>

        <?php
                        foreach ($_SESSION['cart'] as $datos) {
                          $Tprice = $datos['PRICE'] + $Tprice;
                        ?>
          <tr class="">
            <td data-th="Product">
              <div class="row">
                <div class="col-sm-2"><img src="<?php echo $datos['URL']; ?>" class="img-fluid" /></div>
                <div class="col-sm-10">
                  <h4 class="nomargin"><?php echo $datos['NAME']; ?></h4>
                  <p>
                    <?php echo $datos['SHORT']; ?>
                  </p>
                </div>
              </div>
            </td>
            <td data-th="Price">
              <?php echo $datos['PRICE']." €"; ?>
            </td>
            <td data-th="Quantity" class="text-center">
              <?php echo $datos['QUANTITY']; ?>
            </td>
            <td data-th="Subtotal" class="text-center">
              <?php echo $datos['PRICE']*$datos['QUANTITY']." €"; ?>
            </td>
            <td class="actions" data-th="">
              <a class="btn btn-danger btn-sm" href="index.php?controller=order&action=delete_item&id=<?php echo $datos['ID'] ?>">ELIMINAR</a>
            </td>
          </tr>
          <?php } ?>
      </tbody>
      <tfoot>
        <tr>
          <td><a href="index.php" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
          <td colspan="2" class=""></td>
          <td class=" text-center"><strong><?php echo "Total: ".$Tprice." €"; ?></strong></td>
          <td><a href="index.php?controller=order&action=empty_cart" class="btn btn-warning"><i class="fa fa-angle-left">VACÍAR CARRITO</td>
          <td><a href="#" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
        </tr>
      </tfoot>
      <?php } ?>
    </table>
  </div>
</body>

</html>
