<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>GreenDragon - tu carrito</title>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  <link rel="icon" href="view/main/img/main-logo.png">
  <link rel="stylesheet" type="text/css" href="view/main/style/cart_page_style.css">
  <link rel="stylesheet" type="text/css" href="view/main/style/main_page_style.css">
</head>

<body>

  <?php include("view/main/php/header.php");?>

<div class="row">
    <div id="main-content" class="container">
      <?php $summary = 0; ?>
        <table id="cart" class="table table-hover table-responsive">
          <?php if (empty($_SESSION['cart']) && !isset($_SESSION['user'])) {?>
            <div class="container text-center">
              <h3 class="text-info  mt-5">Tu carrito está vacío</h3>
            </div>
          <?php
        } elseif(!empty($_SESSION['cart']) && !isset($_SESSION['user'])) {?>
          <thead>
            <tr>
              <th>Producto</th>
              <th>Precio</th>
              <th>Cantidad</th>
              <th class="text-center">Total</th>
              <th></th>
            </tr>
          </thead>
          <tbody>

            <?php
            foreach ($_SESSION['cart'] as $datos) {
              $summary = ($datos['PRICE']*$datos['QUANTITY']) + $summary;
            ?>
              <tr class="">
                <td data-th="Product">
                  <div class="row">
                    <div class="col-sm-2"><img src="<?php echo $datos['URL']; ?>" class="img-fluid" /></div>
                    <div class="col-sm-10">
                      <h4 class="nomargin"><?php echo $datos['NAME']; ?></h4>
                      <p>
                        <?php echo $datos['SHORTDESCRIPTION']; ?>
                      </p>
                    </div>
                  </div>
                </td>
                <td data-th="Price">
                  <?php echo enEuro($datos['PRICE']); ?>
                </td>
                <td data-th="Quantity" class="text-center">
                  <?php echo $datos['QUANTITY']; ?>
                </td>
                <td data-th="Subtotal" class="text-center">
                  <?php echo enEuro($datos['PRICE']*$datos['QUANTITY']);?>
                </td>
                <td class="actions" data-th="">
                  <a class="btn btn-danger btn-sm" href="index.php?controller=order&action=delete&id=<?php echo $datos['ID'] ?>">Quitar</a>
                </td>
              </tr>
              <?php } ?>
          </tbody>
          <tfoot>
            <tr>
              <td><a href="index.php" class="btn btn-warning">Continuar comprando...</a></td>
              <td colspan="2" class=""></td>
              <td class=" text-center"><strong><?php echo "TOTAL A PAGAR: ".enEuro($summary); ?></strong></td>
              <td><a href="index.php?controller=order&action=empty" class="btn btn-danger">Vaciar Carrito</a></td>
            </tr>
          </tfoot>

        <?php } elseif (isset($_SESSION['user'])){
            if (isset($check) == "PENDING") {?>
          <thead>
            <tr>
              <th>Producto</th>
              <th>Precio</th>
              <th>Cantidad</th>
              <th class="text-center">Total</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <?php
                foreach ($datos as $dato) {
                  $summary = ($dato['PRICE']*$dato['QUANTITY']) + $summary;
                ?>
              <tr class="">
                <td data-th="Product">
                  <div class="row">
                    <div class="col-sm-2"><img src="<?php echo $dato['URL']; ?>" class="img-fluid" /></div>
                    <div class="col-sm-10">
                      <h4 class="nomargin"><?php echo $dato['NAME']; ?></h4>
                      <p>
                        <?php echo $dato['SHORTDESCRIPTION']; ?>
                      </p>
                    </div>
                  </div>
                </td>
                <td data-th="Price">
                  <?php echo enEuro($dato['PRICE']); ?>
                </td>
                <td data-th="Quantity" class="text-center">
                  <?php echo $dato['QUANTITY']; ?>
                </td>
                <td data-th="Subtotal" class="text-center">
                  <?php echo enEuro($dato['PRICE']*$dato['QUANTITY']); ?>
                </td>
                <td class="actions" data-th="">
                  <a class="btn btn-danger btn-sm" href="index.php?controller=order&action=deleteorderitem&id=<?php echo $dato['PRODUCT'] ?>">Quitar</a>
                </td>
              </tr>
              <?php } ?>
          </tbody>
          <tfoot>
            <tr>
              <td><a href="index.php" class="btn btn-warning">Continuar Comprando...</a></td>
              <td colspan="2" class=""></td>
              <td class=" text-center"><strong><?php echo "TOTAL A PAGAR: ".enEuro($summary); ?></strong></td>
              <td><a href="index.php?controller=order&action=emptyorderwithitems" class="btn btn-danger">Vaciar Carrito</a></td>
              <td><a href="index.php?controller=order&action=checkout" class="btn btn-success btn-block">Realizar Pedido</a></td>
            </tr>
          </tfoot>
        <?php } else {?>
          <div class="container text-center">
            <h3 class="text-info  mt-5">Tu carrito está vacío</h3>
          </div>
        <?php  } }?>

        </table>
    </div>
</div>

</body>

</html>
