<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>GreenDragon - Home</title>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  <link rel="icon" href="view/main/img/main-logo.png">
  <link rel="stylesheet" type="text/css" href="view/main/style/main_page_style.css">
  <script src="view/main/js/popover-top-button.js"></script>
</head>

<body>
  <nav class="navbar navbar-light bg-dark justify-content-between">
    <a class="navbar-brand text-success display-4" href="#"><img src="view/main/img/main-logo.png" id="main-logo" alt="Dragón verde">Green Dragon</a>
    <form class="form-inline">
      <input class="form-control mr-sm-2 font-weight-bold" type="search" size="35" placeholder="Buscar" aria-label="Buscar">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>
  </nav>
  <nav class="navbar navbar-toggleable-md navbar-light bg-success">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <p>Bienvenido, </p>
    <ul class="nav nav-pills movie-sel-ul text-center">
      <button type="button" id="btn-identificacion" class="btn btn-outline-dark font-weight-bold">Identificarse</button>
      <button type="button" class="btn btn-outline-dark font-weight-bold ml-2">Cesta</button>
    </ul>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <div class="">
          <h3 class="font-weight-bold">Categorías</h3>
          <div class="dropdown-divider text-dark"></div>
        </div>
        <a class="nav-item nav-link" href="#">Componentes</a>
        <a class="nav-item nav-link" href="#">Ordenadores</a>
        <a class="nav-item nav-link" href="#">Periféricos</a>
      </div>
    </div>
  </nav>

  <?php //include("view/main/php/menu.phtml"); ?>

  <div id="carrusel" class="carousel slide" data-ride="carousel">
<!-- Indicators -->
<ul class="carousel-indicators">
  <li data-target="#carrusel" data-slide-to="0" class="active"></li>
  <li data-target="#carrusel" data-slide-to="1"></li>
  <li data-target="#carrusel" data-slide-to="2"></li>
</ul>

<!-- The slideshow -->
<div class="carousel-inner h-50">
  <div class="carousel-item active">
    <img src="view/main/img/a.jpg" alt="Gráfica NVIDIA Titan XP" class="w-100" height="250">
  </div>
  <div class="carousel-item">
    <img src="view/main/img/b.jpg" alt="Placa Base Aorus X399" class="w-100" height="250">
  </div>
  <div class="carousel-item">
    <img src="view/main/img/c.jpg" alt="Razer Gaming Set" class="w-100" height="250">
    <div class="carousel-caption">
        <h3>Información</h3>
        <p>XDDDD.</p>
      </div>
  </div>
</div>

<a class="carousel-control-prev" href="#carrusel" data-slide="prev">
  <span class="carousel-control-prev-icon"></span>
</a>
<a class="carousel-control-next" href="#carrusel" data-slide="next">
  <span class="carousel-control-next-icon"></span>
</a>
</div>
<form action="index.php?controller=productos&action=sortPriceDesc" method="post">
    <input type="submit" class="btn btn-danger"value="Desc precio" />
</form>
<form action="index.php?controller=productos&action=sortPriceAsc" method="post">
    <input type="submit" class="btn btn-danger"value="Asc precio" />
</form>
<form action="index.php?controller=productos&action=sortNombreDesc" method="post">
    <input type="submit" class="btn btn-danger"value="Z-A" />
</form>
<form action="index.php?controller=productos&action=sortNombreAsc" method="post">
    <input type="submit" class="btn btn-danger"value="A-Z" />
</form>
<form action="index.php?controller=productos&action=sortStockDesc" method="post">
    <input type="submit" class="btn btn-danger"value="Stock Desc" />
</form>
<form action="index.php?controller=productos&action=sortStockAsc" method="post">
    <input type="submit" class="btn btn-danger"value="Stock asc" />
</form>
<?php
include("view/main/php/show_long_desc.phtml");
 ?>
<form action="index.php?controller=usuarios&action=logout" method="post">
        <input type="submit" name="logout" value="CERRAR SESIÓN">
    </form>
</body>

</html>
