<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>GreenDragon - Home</title>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  <link rel="icon" href="view/main/img/main-logo.png">
  <link rel="stylesheet" type="text/css" href="view/main/style/main_page_style.css">
  <script src="view/main/js/popover-top-button.js"></script>
</head>

<body>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#filtros">filtros xd</button>

  <?php
  include("view/main/php/header.php");
  include("view/main/php/filtros.php");
  include("view/main/php/menu.php");
  if(isset($mostrarCarr)){
  include("view/main/php/carrusel.php");
}
  //include("view/main/php/ordenar.php");
  include("view/main/php/mostrar_productos.php");
  //include("view/main/php/pagination.php");
//  include("view/main/php/footer.php");


?>

</body>

</html>
