<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Green Dragon - Historial de compras</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link rel="icon" href="view/main/img/main-logo.png">
  </head>
  <body>
    <?php
    include("view/main/php/header.php");?>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Producto</th>
          <th>Descripción</th>
          <th>Precio</th>
          <th>Cantidad</th>
          <th>Fecha</th>
        </tr>
      </thead>
      <tbody>
        <?php $summary = 0; ?>
        <?php foreach ($records as $record){ ?>
        <tr>
          <th scope="row"><?php echo $record['NAME'] ?></th>
          <td><?php echo $record['SHORTDESCRIPTION'] ?></td>
          <td> <?php echo "500" ?></td>
          <td><?php echo $record['QUANTITY'] ?></td>
          <td><?php echo $record['DATE'] ?></td>
        </tr>
<?php } ?>
      </tbody>
    </table>
  </body>
</html>
