INSERT INTO `BRAND` (`ID`, `NAME`) VALUES (NULL, 'INTEL'), (NULL, 'AMD'), (NULL, 'ASUS'),
 (NULL, 'ACER'), (NULL, 'HP'), (NULL, 'LG'), (NULL, 'LENOVO'), (NULL, 'CORSAIR'), (NULL, 'SAMSUNG'),
  (NULL, 'SEAGATE'), (NULL, 'WESTERN DIGITAL'), (NULL, 'EVGA'), (NULL, 'MSI'), (NULL, 'ALIENWARE'),
   (NULL, 'LOGITECH'), (NULL, 'RAZER'), (NULL, 'PHILIPS'), (NULL, 'GIGABYTE'), (NULL, 'ASROCK'), (NULL, 'G.SKILL');

INSERT INTO `CATEGORY` (`ID`, `NAME`, `PARENTCATEGORY`) VALUES (NULL, 'COMPONENTES', NULL),
 (NULL, 'ORDENADORES', NULL), (NULL, 'PERIFÉRICOS', NULL), (NULL, 'TV', NULL), (NULL, 'SMARTHPHONES', NULL);

 INSERT INTO `CATEGORY` (`ID`, `NAME`, `PARENTCATEGORY`) VALUES (NULL, 'PLACAS BASE', '1'),
  (NULL, 'PROCESADORES', '1'), (NULL, 'TARJETAS GRÁFICAS', '1'), (NULL, 'DISCOS DUROS', '1'),
   (NULL, 'PORTÁTILES', '2'), (NULL, 'PORTÁTILES GAMING', '2'), (NULL, 'SOBREMESA', '2'),
    (NULL, 'SOBREMESA GAMING', '2'), (NULL, 'TECLADOS', '3'), (NULL, 'RATONES', '3'),
     (NULL, 'MONITORES', '3'), (NULL, 'AURICULARES', '3'), (NULL, 'SMART TV', '4'),
      (NULL, '4K/UHD', '4'), (NULL, 'QLED', '4'), (NULL, 'OLED', '4'),
       (NULL, 'FUNDAS ', '5'), (NULL, 'TARJETAS MICRO SD', '5'),
        (NULL, 'PROTECTORES', '5'), (NULL, 'POWERBANKS', '5');
